### ISSUE TITLE
Server stability [meta]

### ISSUE THREAD

**Issue by queenvictoria** [ckutay/Language#2]
- [ ] Restart MySQL (in backup script below)
- [ ] Test reboot VM
- [ ] Upgrade packages
- [ ] Examine Apache error logs
